console.log(100/4);
console.log((8/2)+5-(-3/2));
console.log("Lorem ipsum dolor sit amet");
console.log(`Lorem ipsum dolor sit amet`);
let number = 8;
number = 15;
console.log(number);
const sum = 8 * 8;
console.log(sum);
const name = "Mihail";
const lastName  = "Frunze";
console.log(name, lastName);